package at.wifi.swdev.praxisteilwissensueberpruefungsaschabrodschneider;

import at.wifi.swdev.praxisteilwissensueberpruefungsaschabrodschneider.data.Dreieck;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author sasch
 */
public class GUIDreieck extends javax.swing.JFrame {

    Dreieck einDreieck;
private InfoDialog dlgInfo;
private HilfeDialog dlgHilfe;
    
    public GUIDreieck() {
        initComponents();
        dlgInfo = new InfoDialog(this);
        dlgHilfe = new HilfeDialog(this);
    }
    
        private void showInfoDialog(){
        dlgInfo.setLocationRelativeTo(this);
        dlgInfo.setVisible(true);
    }
    
            private void showHilfeDialog(){
        dlgHilfe.setLocationRelativeTo(this);
        dlgHilfe.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNeueBerechnung = new javax.swing.JButton();
        lblEingabeInmm = new javax.swing.JLabel();
        txtEingabeA = new javax.swing.JTextField();
        lblMm = new javax.swing.JLabel();
        lblBeschreibungButtonBerechne = new javax.swing.JLabel();
        btnBerechne = new javax.swing.JButton();
        lblFlaeche = new javax.swing.JLabel();
        tfAusgabeFlaeche = new javax.swing.JTextField();
        lblFlaechemm2 = new javax.swing.JLabel();
        lblHoehemm = new javax.swing.JLabel();
        lblUmkreisradiusmm = new javax.swing.JLabel();
        lblInkreisradiusmm = new javax.swing.JLabel();
        lblUmfangmm = new javax.swing.JLabel();
        lblHoehe = new javax.swing.JLabel();
        lblUmkreisradius = new javax.swing.JLabel();
        lblInkreisradius = new javax.swing.JLabel();
        lblUmfang = new javax.swing.JLabel();
        tfAusgabeUmkreisradius = new javax.swing.JTextField();
        tfAusgabeHoehe = new javax.swing.JTextField();
        tfAusgabeInkreisradius = new javax.swing.JTextField();
        tfAusgabeUmfang = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSchliessen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menueDatei = new javax.swing.JMenu();
        menaueNeueBerechnung = new javax.swing.JMenuItem();
        menueSchliessen = new javax.swing.JMenuItem();
        menueHilfe = new javax.swing.JMenu();
        menueAnleitung = new javax.swing.JMenuItem();
        menueInfo = new javax.swing.JMenu();
        menueVersionInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUIDreieck");
        setBackground(new java.awt.Color(69, 73, 74));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setResizable(false);

        jToolBar1.setRollover(true);

        btnNeueBerechnung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-icon (1).png"))); // NOI18N
        btnNeueBerechnung.setFocusable(false);
        btnNeueBerechnung.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNeueBerechnung.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNeueBerechnung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeueBerechnungActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNeueBerechnung);

        lblEingabeInmm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEingabeInmm.setText("Bitte geben Sie Seite a an:");

        txtEingabeA.setBackground(new java.awt.Color(51, 153, 0));
        txtEingabeA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEingabeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEingabeAActionPerformed(evt);
            }
        });

        lblMm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMm.setText("mm");

        lblBeschreibungButtonBerechne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBeschreibungButtonBerechne.setText("Drücken Sie den Button zur Berechnung der Werte des Gleichseitigen Dreiecks");

        btnBerechne.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBerechne.setText("Berechne");
        btnBerechne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnBerechne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerechneActionPerformed(evt);
            }
        });

        lblFlaeche.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFlaeche.setText("Fläche:");

        tfAusgabeFlaeche.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfAusgabeFlaeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAusgabeFlaecheActionPerformed(evt);
            }
        });

        lblFlaechemm2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFlaechemm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlaechemm2.setText(" mm²");
        lblFlaechemm2.setMaximumSize(new java.awt.Dimension(30, 20));
        lblFlaechemm2.setMinimumSize(new java.awt.Dimension(30, 20));

        lblHoehemm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHoehemm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoehemm.setText("mm");
        lblHoehemm.setMaximumSize(new java.awt.Dimension(30, 30));
        lblHoehemm.setMinimumSize(new java.awt.Dimension(30, 30));

        lblUmkreisradiusmm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUmkreisradiusmm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUmkreisradiusmm.setText("mm");
        lblUmkreisradiusmm.setMaximumSize(new java.awt.Dimension(30, 30));
        lblUmkreisradiusmm.setMinimumSize(new java.awt.Dimension(30, 30));

        lblInkreisradiusmm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInkreisradiusmm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInkreisradiusmm.setText("mm");
        lblInkreisradiusmm.setMaximumSize(new java.awt.Dimension(30, 30));
        lblInkreisradiusmm.setMinimumSize(new java.awt.Dimension(30, 30));

        lblUmfangmm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUmfangmm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUmfangmm.setText("mm");
        lblUmfangmm.setMaximumSize(new java.awt.Dimension(30, 30));
        lblUmfangmm.setMinimumSize(new java.awt.Dimension(30, 30));

        lblHoehe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoehe.setText("Höhe:");

        lblUmkreisradius.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUmkreisradius.setText("Umkreisradius:");

        lblInkreisradius.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInkreisradius.setText("Inkreisradius:");

        lblUmfang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUmfang.setText("Umfang:");

        tfAusgabeUmkreisradius.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfAusgabeUmkreisradius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAusgabeUmkreisradiusActionPerformed(evt);
            }
        });

        tfAusgabeHoehe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfAusgabeHoehe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAusgabeHoeheActionPerformed(evt);
            }
        });

        tfAusgabeInkreisradius.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfAusgabeInkreisradius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAusgabeInkreisradiusActionPerformed(evt);
            }
        });

        tfAusgabeUmfang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfAusgabeUmfang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAusgabeUmfangActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblStatus.setText("Version 1.0.0.0.1");
        jPanel1.add(lblStatus);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gleichseitiges_Dreieck.png"))); // NOI18N

        btnSchliessen.setText("Schließen");
        btnSchliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchliessenActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menueDatei.setText("Datei");

        menaueNeueBerechnung.setText("Neu");
        menaueNeueBerechnung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menaueNeueBerechnungActionPerformed(evt);
            }
        });
        menueDatei.add(menaueNeueBerechnung);

        menueSchliessen.setText("Schließen");
        menueSchliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueSchliessenActionPerformed(evt);
            }
        });
        menueDatei.add(menueSchliessen);

        jMenuBar1.add(menueDatei);

        menueHilfe.setText("Hilfe");

        menueAnleitung.setText("Anleitung");
        menueAnleitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueAnleitungActionPerformed(evt);
            }
        });
        menueHilfe.add(menueAnleitung);

        jMenuBar1.add(menueHilfe);

        menueInfo.setText("Info");

        menueVersionInfo.setText("Build Info");
        menueVersionInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueVersionInfoActionPerformed(evt);
            }
        });
        menueInfo.add(menueVersionInfo);

        jMenuBar1.add(menueInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUmfang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInkreisradius, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfAusgabeUmfang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUmfangmm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfAusgabeInkreisradius)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInkreisradiusmm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUmkreisradius, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblHoehe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAusgabeHoehe)
                            .addComponent(tfAusgabeUmkreisradius))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoehemm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUmkreisradiusmm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSchliessen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFlaeche, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEingabeInmm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEingabeA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBeschreibungButtonBerechne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBerechne, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfAusgabeFlaeche))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFlaechemm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEingabeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMm)
                    .addComponent(lblEingabeInmm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBerechne, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeschreibungButtonBerechne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlaeche)
                    .addComponent(tfAusgabeFlaeche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlaechemm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoehemm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoehe)
                    .addComponent(tfAusgabeHoehe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUmkreisradiusmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUmkreisradius)
                    .addComponent(tfAusgabeUmkreisradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInkreisradiusmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInkreisradius)
                    .addComponent(tfAusgabeInkreisradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUmfangmm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUmfang)
                    .addComponent(tfAusgabeUmfang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSchliessen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtEingabeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEingabeAActionPerformed
        double seiteA = Double.parseDouble(txtEingabeA.getText());
    }//GEN-LAST:event_txtEingabeAActionPerformed

    private void btnBerechneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerechneActionPerformed
        flaeche();
        hoehe();
        umkreisradius();
        inkreisradius();
        umfang();
        tfAusgabeFlaecheActionPerformed(evt);
    }//GEN-LAST:event_btnBerechneActionPerformed

    public double flaeche() {
        double seiteA = Double.parseDouble(txtEingabeA.getText());
        return Math.sqrt(3) / 4 * (seiteA * seiteA);
    }

    public double hoehe() {
        double seiteA = Double.parseDouble(txtEingabeA.getText());
        return Math.sqrt(3) / 2 * seiteA;
    }

    public double umkreisradius() {
        double seiteA = Double.parseDouble(txtEingabeA.getText());
        return seiteA / Math.sqrt(3);
    }

    public double inkreisradius() {
        double seiteA = Double.parseDouble(txtEingabeA.getText());
        return seiteA / (2 * Math.sqrt(3));
    }

    public double umfang() {
        double seiteA = Double.parseDouble(txtEingabeA.getText());
        return seiteA * 3;
    }

    public void newDocument() {
        tfAusgabeFlaeche.setText("");
        tfAusgabeHoehe.setText("");
        tfAusgabeInkreisradius.setText("");
        tfAusgabeUmfang.setText("");
        tfAusgabeUmkreisradius.setText("");
        txtEingabeA.setText("");
    }

    private void closePrg() {
        int answer = JOptionPane.showConfirmDialog(
                this,
                "Wollen Sie wirklich schließen?",
                "Frage", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (answer == JOptionPane.YES_OPTION) {
            System.out.println("Programm wird geschlossen.");
            this.setVisible(false);
            this.dispose();
            System.exit(0);
        }
    }

    
    
    public void draw(Graphics g) {
        g.drawLine(1, 1, 200, 200);
    }


    private void tfAusgabeFlaecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAusgabeFlaecheActionPerformed

        //Fläche
        String AusgabeFlaeche = String.valueOf(flaeche());
        String AusgabeFlaecheKomma = AusgabeFlaeche.replace(".", ",");
        tfAusgabeFlaeche.setText(AusgabeFlaecheKomma);

        //Höhe
        String AusgabeHoehe = String.valueOf(hoehe());
        String AusgabeHoehekomma = AusgabeHoehe.replace(".", ",");
        tfAusgabeHoehe.setText(AusgabeHoehekomma);

        String AusgabeUmkreisradius = String.valueOf(umkreisradius());
        String AusgabeUmkreisradiuskomma = AusgabeUmkreisradius.replace(".", ",");
        tfAusgabeUmkreisradius.setText(AusgabeUmkreisradiuskomma);

        String AusgabeInkreisradius = String.valueOf(inkreisradius());
        String AusgabeInkreisradiuskomma = AusgabeInkreisradius.replace(".", ",");
        tfAusgabeInkreisradius.setText(AusgabeInkreisradiuskomma);

        String AusgabeUmfang = String.valueOf(umfang());
        String AusgabeUmfangkomma = AusgabeUmfang.replace(".", ",");
        tfAusgabeUmfang.setText(AusgabeUmfangkomma);
    }//GEN-LAST:event_tfAusgabeFlaecheActionPerformed

    private void tfAusgabeHoeheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAusgabeHoeheActionPerformed
    }//GEN-LAST:event_tfAusgabeHoeheActionPerformed

    private void tfAusgabeUmkreisradiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAusgabeUmkreisradiusActionPerformed
    }//GEN-LAST:event_tfAusgabeUmkreisradiusActionPerformed

    private void tfAusgabeInkreisradiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAusgabeInkreisradiusActionPerformed
    }//GEN-LAST:event_tfAusgabeInkreisradiusActionPerformed

    private void tfAusgabeUmfangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAusgabeUmfangActionPerformed
    }//GEN-LAST:event_tfAusgabeUmfangActionPerformed

    private void menaueNeueBerechnungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menaueNeueBerechnungActionPerformed
        newDocument();        // TODO add your handling code here:
    }//GEN-LAST:event_menaueNeueBerechnungActionPerformed

    private void btnNeueBerechnungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeueBerechnungActionPerformed
        newDocument();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNeueBerechnungActionPerformed

    private void btnSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchliessenActionPerformed
        closePrg();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSchliessenActionPerformed

    private void menueSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueSchliessenActionPerformed
        closePrg();        // TODO add your handling code here:
    }//GEN-LAST:event_menueSchliessenActionPerformed

    private void menueAnleitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueAnleitungActionPerformed
showHilfeDialog();        // TODO add your handling code here:
    }//GEN-LAST:event_menueAnleitungActionPerformed

    private void menueVersionInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueVersionInfoActionPerformed
showInfoDialog();        // TODO add your handling code here:
    }//GEN-LAST:event_menueVersionInfoActionPerformed

//    public double flaeche() {
//        double seiteA = Double.parseDouble(txtEingabe.getText());
//        return Math.sqrt(3) / 4 * (seiteA * seiteA);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDreieck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDreieck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDreieck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDreieck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDreieck().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBerechne;
    private javax.swing.JButton btnNeueBerechnung;
    private javax.swing.JButton btnSchliessen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBeschreibungButtonBerechne;
    private javax.swing.JLabel lblEingabeInmm;
    private javax.swing.JLabel lblFlaeche;
    private javax.swing.JLabel lblFlaechemm2;
    private javax.swing.JLabel lblHoehe;
    private javax.swing.JLabel lblHoehemm;
    private javax.swing.JLabel lblInkreisradius;
    private javax.swing.JLabel lblInkreisradiusmm;
    private javax.swing.JLabel lblMm;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUmfang;
    private javax.swing.JLabel lblUmfangmm;
    private javax.swing.JLabel lblUmkreisradius;
    private javax.swing.JLabel lblUmkreisradiusmm;
    private javax.swing.JMenuItem menaueNeueBerechnung;
    private javax.swing.JMenuItem menueAnleitung;
    private javax.swing.JMenu menueDatei;
    private javax.swing.JMenu menueHilfe;
    private javax.swing.JMenu menueInfo;
    private javax.swing.JMenuItem menueSchliessen;
    private javax.swing.JMenuItem menueVersionInfo;
    private javax.swing.JTextField tfAusgabeFlaeche;
    private javax.swing.JTextField tfAusgabeHoehe;
    private javax.swing.JTextField tfAusgabeInkreisradius;
    private javax.swing.JTextField tfAusgabeUmfang;
    private javax.swing.JTextField tfAusgabeUmkreisradius;
    private javax.swing.JTextField txtEingabeA;
    // End of variables declaration//GEN-END:variables

}
